name: Triggered Workflow

on:
  repository_dispatch:
    types: [my-event]
  workflow_dispatch:
    inputs:
      test_lang:
        description: 'Test language'
        required: true
        default: 'TH'
        type: choice
        options:
        - EN
        - TH
jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add the rest of your job steps here
      - name: Set environment variable
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "TEST_ID=m" >> $GITHUB_ENV
            echo "TEST_LANG=${{ github.event.inputs.test_lang }}" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
            echo "TEST_ID=${{ github.event.client_payload.pr-id }}" >> $GITHUB_ENV
            echo "TEST_LANG=TH" >> $GITHUB_ENV
          fi
      - name: echo pr id
        run: |
          echo "pr-id: ${{ github.event.client_payload.pr-id }}"
          echo "env.TEST_ID: ${{ env.TEST_ID }}"
          echo "env.TEST_LANG: ${{ env.TEST_LANG }}"

